using Tycho to test the plugin with Maven
- using the groovy-eclipse-compiler to compile Groovy classes with Maven
- using Tycho 0.18.1 in combination with groovy-eclipse-compiler 2.7.0-01
  as there have been problems with newer versions
- using Eclipse 3.6 "Helios" for testing (currently used for development)
  - the Eclipse version can be changed via the repository url
  - the Groovy-Eclipse version has to be changed accordingly
- explicitly setting the groovy-eclipse-batch version to 1.7.x
  - this makes sure that everything is compiled with Groovy 1.7
    (same as in Eclipse itself)
  - otherwise the groovy-eclipse-compiler plugin can use
    groovy-eclipse-batch 1.8.x
  - this can result in NoClassDefFoundError for ValueRecorder as its
    package changed from Groovy 1.7 to 1.8
- explicitly disabling the ui harness (even if it's disabled by default)